CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE study_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    topic VARCHAR(255) NOT NULL,
    summary TEXT NOT NULL,
    original_content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE flashcards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_set_id BIGINT NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    front TEXT NOT NULL,
    back TEXT NOT NULL
);

CREATE TABLE quiz_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_set_id BIGINT NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    question TEXT NOT NULL,
    options JSONB NOT NULL,
    correct_answer_index INT NOT NULL,
    explanation TEXT NOT NULL
);

CREATE TABLE practice_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_set_id BIGINT NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    focus VARCHAR(255) NOT NULL,
    questions JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE learning_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_set_id BIGINT NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    sections JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE document_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_set_id BIGINT NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    embedding vector(768) NOT NULL,
    chunk_index INT NOT NULL
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_set_id BIGINT NOT NULL REFERENCES study_sets(id) ON DELETE CASCADE,
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_study_sets_user_id ON study_sets(user_id);
CREATE INDEX idx_study_sets_created_at ON study_sets(created_at DESC);
CREATE INDEX idx_flashcards_study_set_id ON flashcards(study_set_id);
CREATE INDEX idx_quiz_questions_study_set_id ON quiz_questions(study_set_id);
CREATE INDEX idx_practice_tests_study_set_id ON practice_tests(study_set_id);
CREATE INDEX idx_practice_tests_created_at ON practice_tests(created_at DESC);
CREATE INDEX idx_learning_plans_study_set_id ON learning_plans(study_set_id);
CREATE INDEX idx_learning_plans_created_at ON learning_plans(created_at DESC);
CREATE INDEX idx_document_chunks_study_set_id ON document_chunks(study_set_id);
CREATE INDEX idx_chat_messages_study_set_id ON chat_messages(study_set_id);
CREATE INDEX idx_chat_messages_created_at ON chat_messages(created_at DESC);
